### ISSUE TITLE
Low on RAM kills the app

### ISSUE THREAD

**Issue by WildS0ft** [Poniverse/Ponyville-Live-Mobile#1]
The app gets killed when the device is low on memory.

**Comment by thomcuddihy** [comment]
This is a known limitation of using Ionic/Cordova, since the multi platform framework doesn't incorporate Android's service design, it can't be prevented from cleanup by the system when resources are low. This is a major driver for the release of the native app (see https://github.com/Poniverse/Ponyville-Live-Android), and will be addressed when that projects replaces the published app (it is currently in active development).
